name: PR
on:
  workflow_dispatch:
    inputs:
      repo:
        description: repo
        required: true
        default: https://github.com/wxy1343/ManifestAutoUpdate
concurrency:
  group: wait
  cancel-in-progress: false
jobs:
  pr:
    runs-on: windows-latest
    steps:
      - name: checkout
        run: git clone --filter=blob:none -b ${{ github.ref_name }} --recurse-submodules https://${{ github.token }}@github.com/${{ github.repository }} .
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: |
          git config --local user.name github-actions[bot]
          git config --local user.email 41898282+github-actions[bot]@users.noreply.github.com
          python pr.py --repo ${{ github.event.inputs.repo || 'https://github.com/wxy1343/ManifestAutoUpdate' }} -t ${{ secrets.token }}